sudo: required
language: generic

services:
  - docker
before_install:
  - docker build -t damsnda/frontend-ang-kub -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run  damsnda/frontend-ang-kub npm run testCI